In [1]:
#On dispose d'une image d'entrée carrée en niveau de gris
from PIL import Image
import numpy as np

def image_to_gray_matrix(image_path):
    """
    Convertit une image en niveaux de gris en une matrice de niveaux de gris.

    :param image_path: Chemin de l'image à convertir.
    :return: Matrice numpy représentant les niveaux de gris de l'image.
    """
    # Charger l'image
    image = Image.open(image_path)

    # Convertir l'image en niveaux de gris si ce n'est pas déjà le cas
    if image.mode != 'L':
        image = image.convert('L')

    # Convertir l'image en matrice numpy
    image_matrix = np.array(image)

    return image_matrix

# Exemple d'utilisation
image_path = 'chemin/vers/votre/image.jpg'
gray_matrix = image_to_gray_matrix(image_path)

print(gray_matrix)


#On détermine le vecteur qui est le centre de gravité c0 de tous les vecteurs
#On split ce vecteur en 2 vecteurs c01=c0+eps et c11=c0-eps
#On classe tous les autres vecteurs de la base d'apprentissage relativement a ces 2 vecteurs en utilisant le critère de la distance euclienne minimale.
#On obtient 2 classes de vecteurs. Pour chaque classe, on calcule le centre de gravité. les deux vecteurs obtenus remplacent c01 et c11.
#On répète jusqu'a ce que la distortion moyenne devienne inferieure a un certain seuil
#A la fin de l'étape précédente on obtient ainsi deux vecteurs qui sont les centres de gravité des deux classes. On split ces deux vecteurs selon la ligne 5 encore, on applique l'étape 3 à nouveau sur ces 2 vecteurs. on s'arrete quand le nombre voulu de vecteurs prototypes (la par exemple on en a 4).
#Une fois le dictionnaire formé, on remplace chaque bloc de l'image par son protoype le plus proche au sens de la distance euclidienne.

[[174 174 174 ... 123 123 123]
 [174 174 174 ... 123 123 123]
 [174 174 174 ... 123 123 123]
 ...
 [ 47  47  47 ...  27  27  27]
 [ 47  47  47 ...  27  27  27]
 [ 47  47  47 ...  27  27  27]]


In [ ]:
#On sépare cette image en bloc de taille NxN
def split_matrix_into_blocks(matrix, block_size):
    """
    Sépare une matrice en blocs de taille NxN.

    :param matrix: Matrice numpy à séparer.
    :param block_size: Taille des blocs NxN.
    :return: Liste de blocs de taille NxN.
    """
    # Obtenir les dimensions de la matrice
    rows, cols = matrix.shape

    # Vérifier que la matrice peut être divisée en blocs de taille NxN
    if rows % block_size != 0 or cols % block_size != 0:
        raise ValueError("La taille de la matrice doit être un multiple de la taille des blocs.")

    # Initialiser la liste de blocs
    blocks = []

    # Séparer la matrice en blocs
    for i in range(0, rows, block_size):
        for j in range(0, cols, block_size):
            block = matrix[i:i + block_size, j:j + block_size]
            blocks.append(block)

    return blocks


In [ ]:
#Chaque bloc est mappé en vecteur de dimension N²
def block_to_vector(block):
    """
    Transforme un block de taille N en un vecteur de dimension n² en empilant les colonnes.
    
    """
    # Vérifier que le block est carré
    rows, cols = block.shape
    if rows != cols:
        raise ValueError("La matrice doit être carrée.")

    # Empiler les colonnes de la matrice l'une en dessous de l'autre
    vector = matrix.T.flatten()

    return vector

def matrix_to_vectors(blocks_list):
    matrix_list
    for k in range(len(blocks_list)):
        